//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.Hels.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class AppsAboutSetings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppsAboutSetings defaultInstance = ((AppsAboutSetings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppsAboutSetings())));
        
        public static AppsAboutSetings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AssemblyCompany {
            get {
                return ((string)(this["AssemblyCompany"]));
            }
            set {
                this["AssemblyCompany"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AssemblyCopyright {
            get {
                return ((string)(this["AssemblyCopyright"]));
            }
            set {
                this["AssemblyCopyright"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AssemblyDescription {
            get {
                return ((string)(this["AssemblyDescription"]));
            }
            set {
                this["AssemblyDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AssemblyProduct {
            get {
                return ((string)(this["AssemblyProduct"]));
            }
            set {
                this["AssemblyProduct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AssemblyVersion {
            get {
                return ((string)(this["AssemblyVersion"]));
            }
            set {
                this["AssemblyVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AssemblyFileVersion {
            get {
                return ((string)(this["AssemblyFileVersion"]));
            }
            set {
                this["AssemblyFileVersion"] = value;
            }
        }
    }
}
