//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.Hels.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class FormsColor : global::System.Configuration.ApplicationSettingsBase {
        
        private static FormsColor defaultInstance = ((FormsColor)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FormsColor())));
        
        public static FormsColor Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 224, 192")]
        public global::System.Drawing.Color ForeColorAll {
            get {
                return ((global::System.Drawing.Color)(this["ForeColorAll"]));
            }
            set {
                this["ForeColorAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PainelFundo {
            get {
                return ((global::System.Drawing.Color)(this["PainelFundo"]));
            }
            set {
                this["PainelFundo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color PainelTopBooton {
            get {
                return ((global::System.Drawing.Color)(this["PainelTopBooton"]));
            }
            set {
                this["PainelTopBooton"] = value;
            }
        }
    }
}
