// <auto-generated />
using System;
using DataEntityFrameWork.Controllers.Helps;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataEntityFrameWork.Migrations
{
    [DbContext(typeof(AppProfessorContext))]
    [Migration("20190405072014_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataEntityFrameWork.Models.Alunos", b =>
                {
                    b.Property<int>("AlunosID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Nome");

                    b.Property<int>("Repetente");

                    b.Property<int>("TurmasID");

                    b.HasKey("AlunosID");

                    b.HasIndex("TurmasID");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("DataEntityFrameWork.Models.Classes", b =>
                {
                    b.Property<int>("ClassesID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassesNome");

                    b.HasKey("ClassesID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("DataEntityFrameWork.Models.Cursos", b =>
                {
                    b.Property<int>("CursosID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CursosNome");

                    b.Property<string>("Descricao");

                    b.Property<string>("Sigra");

                    b.HasKey("CursosID");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("DataEntityFrameWork.Models.Escola", b =>
                {
                    b.Property<int>("EscolaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Imagem");

                    b.Property<string>("Ministerio");

                    b.Property<string>("Nome");

                    b.Property<string>("Outros");

                    b.Property<string>("Rodape");

                    b.Property<string>("republica");

                    b.HasKey("EscolaID");

                    b.ToTable("Escola");
                });

            modelBuilder.Entity("DataEntityFrameWork.Models.Faltas", b =>
                {
                    b.Property<int>("FaltasID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlunosID");

                    b.Property<DateTime>("DataHoje");

                    b.Property<int>("FaltasNumeros");

                    b.Property<string>("Justificacao");

                    b.Property<bool>("faltou");

                    b.HasKey("FaltasID");

                    b.HasIndex("AlunosID");

                    b.ToTable("Faltas");
                });

            modelBuilder.Entity("DataEntityFrameWork.Models.FaltasLogs", b =>
                {
                    b.Property<int>("FaltasLogsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data");

                    b.Property<string>("Descricao");

                    b.HasKey("FaltasLogsID");

                    b.ToTable("FaltasLogs");
                });

            modelBuilder.Entity("DataEntityFrameWork.Models.Periodo", b =>
                {
                    b.Property<int>("PeriodoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<string>("PeriodoNome");

                    b.HasKey("PeriodoID");

                    b.ToTable("Periodo");
                });

            modelBuilder.Entity("DataEntityFrameWork.Models.Trimestres", b =>
                {
                    b.Property<int>("TrimestreID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<int>("Inicio");

                    b.Property<int>("Termino");

                    b.Property<string>("TrimestreNome");

                    b.HasKey("TrimestreID");

                    b.ToTable("Trimestres");
                });

            modelBuilder.Entity("DataEntityFrameWork.Models.Turmas", b =>
                {
                    b.Property<int>("TurmasID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassesID");

                    b.Property<int>("CursosID");

                    b.Property<string>("Descricao");

                    b.Property<int>("IdadeFim");

                    b.Property<int>("IdadeInicio");

                    b.Property<int>("PeriodoID");

                    b.Property<int>("Quantidade");

                    b.Property<string>("Sala");

                    b.Property<string>("TurmasNome");

                    b.HasKey("TurmasID");

                    b.HasIndex("ClassesID");

                    b.HasIndex("CursosID");

                    b.HasIndex("PeriodoID");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("DataEntityFrameWork.Models.Usuarios", b =>
                {
                    b.Property<int>("UsuariosID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data");

                    b.Property<string>("Email");

                    b.Property<string>("Login");

                    b.Property<string>("Pin");

                    b.Property<string>("Senha");

                    b.HasKey("UsuariosID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DataEntityFrameWork.Models.Alunos", b =>
                {
                    b.HasOne("DataEntityFrameWork.Models.Turmas", "Turmas")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmasID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataEntityFrameWork.Models.Faltas", b =>
                {
                    b.HasOne("DataEntityFrameWork.Models.Alunos", "Alunos")
                        .WithMany("Faltas")
                        .HasForeignKey("AlunosID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataEntityFrameWork.Models.Turmas", b =>
                {
                    b.HasOne("DataEntityFrameWork.Models.Classes", "Classes")
                        .WithMany("Turmas")
                        .HasForeignKey("ClassesID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataEntityFrameWork.Models.Cursos", "Cursos")
                        .WithMany("Turmas")
                        .HasForeignKey("CursosID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataEntityFrameWork.Models.Periodo", "Periodo")
                        .WithMany("Turmas")
                        .HasForeignKey("PeriodoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
